Upgrade jsdom to fix test errors
`npm test` failed with error text like this:

```
Error: The module 'node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108.
canvas was compiled against a different Node.js version
```

Version 93 is a v16 release, but the project version is on 18 now.

A `uninstall` and a new `install -D` got the jsdom tests working.